const translations = {
    en: {
        //Header
        "popup-title": "OPEN IN THE LOBBY",
        "popup-desc": "Continue if you are in the Black Ops 7 lobby.",
        "popup-btn": "Continue",
        "status-title": "Status",
        "status-desc": "View service status",

        // Settings
        "nav-settings": "Settings",
        "lang-title": "Language",
        "lang-desc": "Change the language to your preference",
        "settings-title": "Settings",
        "settings-desc": "Customize the Profiles app and more",
        "save-title": "Save Profile",
        "save-desc": "Save after each change",
        "save-btn": "Save",

        // Radar
        "radar-title": "Radar",
        "radar-desc": "Customize the basic 2D radar",
        "uav-title": "Enable UAV Advanced",
        "uav-desc": "Enable advanced UAV on the large map",
        "shape-title": "Radar Shape",
        "shape-desc": "Choose your radar style",
        "posh-title": "Horizontal Position",
        "posh-desc": "Move the radar from right to left",
        "posv-title": "Vertical Position",
        "posv-desc": "Move the radar up and down",
        "vis-title": "Colors Visuals",
        "vis-desc": "Customize the radar colors and more",
        "bg-title": "Show Background",
        "bg-desc": "Toggle radar background fill",
        "lines-title": "Show Lines",
        "lines-desc": "Show T & Y center guides",
        "rbg-title": "Radar Background",
        "rbg-desc": "Set the radar background color",
        "rline-title": "Radar Lines",
        "rline-desc": "Change the color of grid lines",
        "evis-title": "Enemy Visible",
        "evis-desc": "Color for enemies in direct sight",
        "ehid-title": "Enemy Hidden",
        "ehid-desc": "Color for enemies behind cover",

        //Loot ESP
        "loot-title": "Loot ESP",
        "loot-desc": "Customize and display map items",
        "loot-lines-title": "Show Lines",
        "loot-lines-desc": "Draw a line towards the loot",
        "loot-thick-title": "Line Thickness",
        "loot-thick-desc": "Increase the thickness of the lines",
        "loot-dist-title": "Show Distance Text",
        "loot-dist-desc": "Displays the distance to items",
        "loot-font-title": "Font Size",
        "loot-font-desc": "Change the size of the text",
        "loot-clin-title": "Color Lines",
        "loot-clin-desc": "Change the lines color",
        "loot-ctxt-title": "Color Text",
        "loot-ctxt-desc": "Change the text color",
        "loot-filter-title": "Item Filter",
        "loot-filter-desc": "Select items to display on ESP",
        "loot-wait": "Waiting for item list...",

        // Aimbot
        
        "aim-title": "Aimbot",
        "aim-desc": "Modify the values to adjust the aimbot.",
        "aim-input": "Input Device",
        "aim-input-desc": "Select the input device",
        "aim-key": "Aim Key",
        "aim-key-desc": "Capture your button or key",
        "aim-key2": "Aim Key Second",
        "aim-bone": "Target Bone",
        "aim-bone-desc": "Bone position in the target",
        "aim-panic": "Panic Mode",
        "aim-panic-desc": "Aggressive Mode",
        "aim-pkey": "Panic Key",
        "aim-pred": "Prediction Aimbot",
        "aim-pred-desc": "Predicts enemy movement",
        "aim-vis": "Visible Only",
        "aim-vis-desc": "Only target visible enemies",
        "aim-down": "Ignore Downed",
        "aim-down-desc": "Disable aimbot on downed enemies",
        "aim-lock": "Aim Lock",
        "aim-lock-desc": "Lock onto target tracking",
        "aim-smooth": "Smooth Aim",
        "aim-smooth-desc": "Adjust the aimbot smoothness",
        "aim-dist": "Distance Aim",
        "aim-dist-desc": "Adjust the aimbot max distance",
        "fov-title": "FOV Settings",
        "fov-show": "Show FOV",
        "fov-show-desc": "Draw the circle on screen",
        "fov-size": "FOV Size",
        "fov-size-desc": "Adjust the size of the FOV",
        "fov-rgb": "FOV RGB Mode",
        "fov-rgb-desc": "Dynamic colors for the FOV",
        "fov-speed": "Speed Color RGB",
        "fov-speed-desc": "Adjust the RGB color speed",

        // ESP
        "vis-title": "ESP Visuals",
        "vis-desc": "Activate or deactivate ESP on enemies",
        "vis-box": "ESP Box",
        "vis-box-desc": "Draw the enemy box",
        "vis-tbox": "Type Box",
        "vis-tbox-desc": "Choose the type of box",
        "vis-thick": "Box Thickness",
        "vis-thick-desc": "Increase the thickness of the box",
        "vis-fill": "Box Filled",
        "vis-fill-desc": "Fill the box with a background",
        "vis-opac": "Filled Opacity Box",
        "vis-opac-desc": "Adjust the background opacity",
        "vis-weapon": "Show Weapon",
        "vis-weapon-desc": "Show enemy weapon",
        "vis-plat": "Show Platform",
        "vis-plat-desc": "Show enemy platform",
        "vis-name": "ESP Name Text",
        "vis-name-desc": "Show enemy names",
        "vis-dist": "ESP Distance Text",
        "vis-dist-desc": "Show distance to enemies",
        "vis-font": "Font Size",
        "vis-font-desc": "Increase text size",
        "vis-hp": "ESP Healthbar",
        "vis-hp-desc": "Show enemy health bar",
        "vis-skel": "ESP Skeleton",
        "vis-skel-desc": "Show enemy bones",
        "vis-head": "Show Bone Head",
        "vis-head-desc": "Draw skull on head",
        "vis-sthick": "Skeleton Thickness",
        "vis-sthick-desc": "Increase bone thickness",
        "vis-ind": "Show Indicator",
        "vis-ind-desc": "Indicator for off-screen enemies",
        "vis-line": "ESP Line",
        "vis-line-desc": "Draw line toward enemy",
        "vis-lpos": "Line Positions",
        "vis-lpos-desc": "Line start position",
        "vis-maxd": "Max Distance",
        "vis-maxd-desc": "Max distance for ESP",
        "vis-ctitle": "Colors Visuals",
        "vis-cdesc": "Customize ESP colors",
        "vis-ctxt": "ESP Text Color",
        "vis-cvis": "Enemy Visible Color",
        "vis-cinvis": "Enemy Invisible Color",
        "vis-cdown": "Enemy Color Downed"


    },
    es: {
        //Header
        "popup-title": "ABRIR EN EL LOBBY",
        "popup-desc": "Continuar si estas en el lobby de Black Ops 7.",
        "popup-btn": "Continuar",
        "status-title": "Estado",
        "status-desc": "Ver el estado del servicio",

         // Settings
        "nav-settings": "Ajustes",
        "lang-title": "Idioma",
        "lang-desc": "Cambia el idioma a tu preferencia",
        "settings-title": "Ajustes",
        "settings-desc": "Personaliza perfiles y mas",
        "save-title": "Guardar Perfil",
        "save-desc": "Guardar tras cada cambio",
        "save-btn": "Guardar",

        // Radar 
        "radar-title": "Radar",
        "radar-desc": "Personaliza el radar 2D basico",
        "uav-title": "Activar UAV Avanzado",
        "uav-desc": "Activa UAV avanzado en el mapa",
        "shape-title": "Forma del Radar",
        "shape-desc": "Elige el estilo de tu radar",
        "posh-title": "Posicion Horizontal",
        "posh-desc": "Mueve el radar de derecha a izquierda",
        "posv-title": "Posicion Vertical",
        "posv-desc": "Mueve el radar de arriba a abajo",
        "vis-title": "Colores Visuales",
        "vis-desc": "Personaliza colores del radar",
        "bg-title": "Mostrar Fondo",
        "bg-desc": "Activa el relleno del radar",
        "lines-title": "Mostrar Lineas",
        "lines-desc": "Muestra guias centrales T y Y",
        "rbg-title": "Fondo del Radar",
        "rbg-desc": "Color de fondo y opacidad",
        "rline-title": "Lineas del Radar",
        "rline-desc": "Color de las lineas de la cuadricula",
        "evis-title": "Enemigo Visible",
        "evis-desc": "Color de enemigos a la vista",
        "ehid-title": "Enemigo Oculto",
        "ehid-desc": "Color de enemigos tras cobertura",

        // Loot ESP
        "loot-title": "Botin ESP",
        "loot-desc": "Personaliza los objetos del mapa",
        "loot-lines-title": "Mostrar Lineas",
        "loot-lines-desc": "Dibuja una linea hacia el botin",
        "loot-thick-title": "Grosor de Linea",
        "loot-thick-desc": "Aumenta el grosor de las lineas",
        "loot-dist-title": "Mostrar Distancia",
        "loot-dist-desc": "Muestra la distancia de los objetos",
        "loot-font-title": "Tamano de Fuente",
        "loot-font-desc": "Cambia el tama�o del texto",
        "loot-clin-title": "Color de Lineas",
        "loot-clin-desc": "Cambia el color de las lineas",
        "loot-ctxt-title": "Color de Texto",
        "loot-ctxt-desc": "Cambia el color del texto",
        "loot-filter-title": "Filtro de Objetos",
        "loot-filter-desc": "Selecciona que objetos mostrar",
        "loot-wait": "Esperando lista de objetos...",

        // Aimbot
        "aim-title": "Aimbot",
        "aim-desc": "Modifica los valores para ajustar el apuntado",
        "aim-input": "Dispositivo de Entrada",
        "aim-input-desc": "Selecciona el dispositivo de entrada",
        "aim-key": "Tecla de Apuntado",
        "aim-key-desc": "Captura tu boton o tecla",
        "aim-key2": "Segunda Tecla",
        "aim-bone": "Hueso Objetivo",
        "aim-bone-desc": "Posicion del hueso en el objetivo",
        "aim-panic": "Modo Panico",
        "aim-panic-desc": "Modo Agresivo",
        "aim-pkey": "Tecla Panico",
        "aim-pred": "Prediccion",
        "aim-pred-desc": "Predice el movimiento del enemigo",
        "aim-vis": "Solo Visibles",
        "aim-vis-desc": "Solo apunta a enemigos visibles",
        "aim-down": "Ignorar Caidos",
        "aim-down-desc": "Desactiva aimbot en enemigos caidos",
        "aim-lock": "Fijar Objetivo",
        "aim-lock-desc": "Mantiene el fijado del objetivo",
        "aim-smooth": "Suavizado",
        "aim-smooth-desc": "Ajusta la suavidad del apuntado",
        "aim-dist": "Distancia de Apuntado",
        "aim-dist-desc": "Ajusta la distancia maxima",
        "fov-title": "Ajustes de FOV",
        "fov-show": "Mostrar FOV",
        "fov-show-desc": "Dibuja el circulo en pantalla",
        "fov-size": "Tama�o de FOV",
        "fov-size-desc": "Ajusta el tama�o del circulo",
        "fov-rgb": "Modo RGB",
        "fov-rgb-desc": "Colores dinamicos para el FOV",
        "fov-speed": "Velocidad RGB",
        "fov-speed-desc": "Ajusta la velocidad del color",

        // ESP
        "vis-title": "Visuales ESP",
        "vis-desc": "Activa o desactiva ESP en enemigos",
        "vis-box": "Caja ESP",
        "vis-box-desc": "Dibuja la caja del enemigo",
        "vis-tbox": "Tipo de Caja",
        "vis-tbox-desc": "Elige el estilo de la caja",
        "vis-thick": "Grosor de Caja",
        "vis-thick-desc": "Aumenta el grosor de la caja",
        "vis-fill": "Caja Rellena",
        "vis-fill-desc": "Rellena la caja con fondo",
        "vis-opac": "Opacidad de Relleno",
        "vis-opac-desc": "Ajusta la opacidad del fondo",
        "vis-weapon": "Mostrar Arma",
        "vis-weapon-desc": "Muestra el arma del enemigo",
        "vis-plat": "Mostrar Plataforma",
        "vis-plat-desc": "Muestra la plataforma del enemigo",
        "vis-name": "Texto de Nombre",
        "vis-name-desc": "Muestra el nombre del enemigo",
        "vis-dist": "Texto de Distancia",
        "vis-dist-desc": "Muestra la distancia al enemigo",
        "vis-font": "Tama�o de Fuente",
        "vis-font-desc": "Aumenta el tama�o del texto",
        "vis-hp": "Barra de Vida",
        "vis-hp-desc": "Muestra la vida del enemigo",
        "vis-skel": "Esqueleto ESP",
        "vis-skel-desc": "Muestra los huesos del enemigo",
        "vis-head": "Mostrar Cabeza",
        "vis-head-desc": "Dibuja un circulo en la cabeza",
        "vis-sthick": "Grosor de Esqueleto",
        "vis-sthick-desc": "Aumenta el grosor de los huesos",
        "vis-ind": "Mostrar Indicador",
        "vis-ind-desc": "Indicador de enemigos fuera de pantalla",
        "vis-line": "Lineas ESP",
        "vis-line-desc": "Dibuja una linea hacia el enemigo",
        "vis-lpos": "Posicion de Linea",
        "vis-lpos-desc": "Punto de inicio de la linea",
        "vis-maxd": "Distancia Maxima",
        "vis-maxd-desc": "Distancia maxima del ESP",
        "vis-ctitle": "Colores Visuales",
        "vis-cdesc": "Personaliza colores del ESP",
        "vis-ctxt": "Color de Texto",
        "vis-cvis": "Color Enemigo Visible",
        "vis-cinvis": "Color Enemigo Invisible",
        "vis-cdown": "Color Enemigo Caido"

    }
};