
const weaponNames = {
 "sat_mp_remote_robot_arm_gun":"PLACEHOLDER FOR REMOTE ROBOT DM WEAPON",
 "sat_me_shockbaton":"Flatline MK.II",
 "sat_la_polis":"A.R.C. M1",
 "sat_pi_timir":"Jäger 45",
 "sat_sh_corso":"M10 Breacher",
 "sat_sn_baltic":"XR-3 Ion",
 "sat_lm_hades":"MK.78",
 "sat_dm_scotia":"M8A1",
 "sat_sm_komodo":"Razor 9mm",
 "sat_sm_orca":"Ryden 45K",
 "sat_ar_eagle":"MXR-17",
 "sat_ar_condor":"Peacekeeper Mk1",
 "sat_ar_hawk":"M15 MOD 0",
 "sat_pi_atlas":"CODA 9",
 "sat_sh_husky":"Echo 12",
 "sat_sn_drake":"VS Recon",
 "sat_sm_zebra":"Dravec 45",
 "sat_me_zombie_melee":"NA",
 "t10_knifestab":"Knife",
 "t10_me_diveknife":"Knife",
 "t10_swimfists":"Fists",
 "t10_me_climbfists":"Fists",
 "t10_me_fists":"None",
 "t10_pi_p19_raygunmark2":"NA",
 "t10_pi_p19_raygun":"NA",
 "t10_la_mangler_cannon":"Mangler Cannon",
 "sat_usa_training_course_bot":"NA",
 "sat_remote_robot_guild":"BRUTUS",
 "sat_ind_pl_violet":"ZAVERI",
 "sat_mex_pl_indigo":"JURADO",
 "sat_chn_pl_gold":"WEI LIN",
 "sat_nzl_pl_rose":"50/50",
 "sat_usa_pl_red":"MASON",
 "sat_mex_pl_green":"KAGAN",
 "sat_ind_pl_azure":"FALKNER",
 "sat_zaf_pl_peach":"VERMAAK",
 "sat_usa_pl_jill_base":"SAT_USA_PL_JILL_BASE",
 "sat_remote_robot":"BRUTUS",
 "sat_usa_pl_jack_base":"SAT_USA_PL_JACK_BASE",
 "t10_usa_pl_jill_base":"JILL",
 "t10_usa_pl_jack_base":"JACK",
 "sat_camo_pap_firefly_03":"#PH,SAT_CAMOS/SAT_CAMO_PAP_FIREFLY_03",
 "sat_camo_pap_firefly_02":"#PH,SAT_CAMOS/SAT_CAMO_PAP_FIREFLY_02",
 "sat_camo_pap_firefly_01":"#PH,SAT_CAMOS/SAT_CAMO_PAP_FIREFLY_01",
 "sat_equip_cluster_grenade_rec":"NA",
 "sat_equip_cluster_grenade_submunition_rec":"NA",
 "sat_grip_mixgrip_ar_eagle_comb":"Virgil-XI Comb",
 "sat_grip_quickdraw2_ar_eagle_comb":"Aria Assail Comb",
 "sat_grip_sprintout_ar_eagle_comb":"Bell-H81 Comb",
 "sat_grip_sprintout2_ar_eagle_comb":"Fissure Comb",
 "sat_grip_quickdraw_ar_eagle_comb":"Celerity Comb",
 "sat_microreflex06_pi_tall":"Kepler Prism-IX Mini",
 "sat_microreflex06_pi":"Kepler Prism-IX Mini",
 "sat_scope_pi_tall":"Bowen Scout Scope",
 "sat_pro_gas_grenade_mod_1":"Acidic Compound",
 "sat_pro_gas_grenade_stats_1":"Distilled Compound",
 "sat_pro_combat_link_stats_1":"Frequency Booster",
 "sat_pro_combat_link_mod_1":"Command Relay",
 "sat_ar_hawk_microreflex01_ar_beta":"NA",
 "sat_ar_hawk_mag_extmag_beta":"NA",
 "sat_ar_hawk_bar_mixbarrel_beta":"NA",
 "sat_ar_hawk_grip_beta":"NA",
 "sat_ar_hawk_stock_hipfiremove_beta":"NA",
 "sat_ar_hawk_rec_beta":"NA",
 "sat_microreflex05_pi_tall":"Bowen Pixel Reflex",
 "sat_ammo_12g_sh_corso":"Default Ammo",
 "sat_microreflex01_pi_tall":"LTI Mini",
 "sat_microreflex04_pi_tall":"EAM Micro Dot",
 "sat_equip_gas_grenade_rec":"NA",
 "sat_pro_concussion_stats_1":"Longer Stun",
 "sat_pro_concussion_mod_1":"Stronger Stun",
 "sat_microreflex05_pi":"Bowen Pixel Reflex",
 "sat_pro_adrenaline_mod_1":"Combat Performance Boost",
 "sat_pro_adrenaline_stats_1":"Cleanse",
 "sat_pro_dart_mark_zero_mod_1":"Rotor Boost",
 "sat_pro_dart_mark_zero_stats_1":"High Density Explosive",
 "sat_pro_trophy_stats_1":"High Efficiency Battery",
 "sat_pro_trophy_mod_1":"Tighter Packing",
 "sat_pro_assault_pack_stats_1":"High Efficiency Battery",
 "sat_pro_assault_pack_mod_1":"Lucky Ammo",
 "sat_pro_semtex_stats_1":"High Density Explosive",
 "sat_pro_drone_launcher_mod_1":"Radar Link",
 "sat_pro_mini_sentry_stats_1":"Rapid Fire Mod",
 "sat_pro_drone_launcher_stats_1":"Quick Launcher",
 "sat_pro_semtex_mod_1":"Controllable Fuse",
 "sat_pro_mini_sentry_mod_1":"Gyroscopic Stabilizer",
 "sat_equip_frag_rec":"NA",
 "sat_pro_combat_axe_stats_1":"Lightweight Alloys",
 "sat_pro_combat_axe_mod_1":"Ergonomic Grip",
 "sat_rec_me_shockbaton":"Default Receiver",
 "sat_pro_flash_grenade_stats_1":"Brighter Burn",
 "sat_pro_flash_grenade_mod_1":"Repeater",
 "sat_ub_gl_smoke_dm_scotia":"Launcher - Smoke",
 "sat_ub_gl_dc_dm_scotia":"Launcher - Drill Charge",
 "sat_ub_gl_he_dm_scotia":"Launcher - High Explosive",
 "sat_ub_gl_std_dm_scotia":"Launcher - Standard",
 "sat_muzzle_mono_suppressor_sm_zebra":"Monolithic Suppressor",
 "sat_muzzle_mono_suppressor_ar_eagle":"Monolithic Suppressor",
 "sat_muzzle_mono_suppressor_sn_baltic":"Monolithic Suppressor",
 "sat_muzzle_mono_suppressor_dm_scotia":"Monolithic Suppressor",
 "sat_muzzle_mono_suppressor_sh_husky":"Monolithic Suppressor",
 "sat_muzzle_mono_suppressor_sh_corso":"Monolithic Suppressor",
 "sat_muzzle_mono_suppressor_sm_komodo":"Monolithic Suppressor",
 "sat_muzzle_mono_suppressor_pi_timir":"Monolithic Suppressor",
 "sat_muzzle_mono_suppressor_pi_atlas":"Monolithic Suppressor",
 "sat_muzzle_mono_suppressor_lm_hades":"Monolithic Suppressor",
 "sat_muzzle_mono_suppressor_sm_orca":"Monolithic Suppressor",
 "sat_muzzle_mono_suppressor_ar_hawk":"Monolithic Suppressor",
 "sat_muzzle_mono_suppressor_sn_drake":"Monolithic Suppressor",
 "sat_muzzle_mono_suppressor_ar_condor":"Monolithic Suppressor",
 "sat_ammo_12g_db_sh_corso":"12 Gauge Dragon's Breath",
 "sat_ammo_12g_slug_sh_husky":"12 Gauge Slug",
 "sat_ammo_12g_slug_sh_corso":"12 Gauge Slug",
 "sat_ammo_12g_db_sh_husky":"12 Gauge Dragon's Breath",
 "sat_rec_pi_atlas":"Default Receiver",
 "sat_rec_ar_hawk":"Default Receiver",
 "sat_rec_ks_remote_robot":"Default Receiver",
 "sat_zm_me_shockbaton":"ZM Attachment",
 "sat_zm_me_shockbaton_pack":"ZM Attachment",
 "sat_firemod_pump_sh_corso":"Pump Guide Rod",
 "sat_firemod_rechamber_sh_husky":"Turnkey Rapid Drum",
 "sat_equip_smoke_rec":"NA",
 "sat_equip_stun_rec":"NA",
 "sat_equip_combat_axe_rec":"NA",
 "sat_equip_flash_rec":"NA",
 "sat_ammo_556n_fmj_dm_scotia":"5.56 NATO FMJ",
 "sat_firemod_springs_ar_eagle":"Recoil Sync Unit",
 "sat_ammo_556n_velocity_ar_hawk":"5.56 NATO Overpressured",
 "sat_ammo_45cal_fmj_pi_timir":".45 Cal FMJ",
 "sat_firemod_springs_sh_corso":"Buffer Spring",
 "sat_ammo_5x28_velocity_ar_condor":"5.7x28mm Overpressured",
 "sat_firemod_springs_sm_komodo":"Accelerated Recoil System",
 "sat_firemod_boltcarrier_pi_atlas":"Bolt Carrier Group",
 "sat_ammo_9x19_fmj_sm_komodo":"9mm Parabellum FMJ",
 "sat_ammo_762n_velocity_lm_hades":"7.62 NATO Overpressured",
 "sat_ammo_762n_fmj_ar_eagle":"7.62 NATO FMJ",
 "sat_firemod_boltcarrier_ar_eagle":"Bolt Carrier Group",
 "sat_firemod_springs_dm_scotia":"Buffer Spring",
 "sat_firemod_springs_pi_atlas":"Recoil Sync Unit",
 "sat_firemod_springs_lm_hades":"Accelerated Recoil System",
 "sat_firemod_boltcarrier_sm_orca":"Bolt Carrier Group",
 "sat_ammo_45cal_fmj_sm_orca":".45 Cal FMJ",
 "sat_firemod_springs_sn_drake":"Accelerated Recoil System",
 "sat_ammo_556n_velocity_dm_scotia":"5.56 NATO Overpressured",
 "sat_ammo_9x19_velocity_sm_komodo":"9mm Parabellum Overpressured",
 "sat_firemod_boltcarrier_ar_condor":"Bolt Carrier Group",
 "sat_ammo_762n_velocity_sn_baltic":"7.62 NATO Overpressured",
 "sat_ammo_45cal_velocity_sm_zebra":".45 Cal Overpressured",
 "sat_firemod_boltcarrier_lm_hades":"Bolt Carrier Group",
 "sat_ammo_45cal_fmj_sm_zebra":".45 Cal FMJ",
 "sat_firemod_boltcarrier_dm_scotia":"Bolt Carrier Group",
 "sat_ammo_45cal_velocity_pi_timir":".45 Cal Overpressured",
 "sat_firemod_boltcarrier_ar_hawk":"Bolt Carrier Group",
 "sat_ammo_5x28_fmj_ar_condor":"5.7x28mm FMJ",
 "sat_firemod_charge_sn_baltic":"Quick Charge",
 "sat_ammo_762n_fmj_lm_hades":"7.62 NATO FMJ",
 "sat_ammo_762n_fmj_sn_baltic":"7.62 NATO FMJ",
 "sat_firemod_springs_sm_orca":"Recoil Sync Unit",
 "sat_firemod_boltcarrier_sm_zebra":"Bolt Carrier Group",
 "sat_ammo_762n_velocity_ar_eagle":"7.62 NATO Overpressured",
 "sat_ammo_9x19_fmj_pi_atlas":"9mm Parabellum FMJ",
 "sat_ammo_762n_velocity_sn_drake":"7.62 NATO Overpressured",
 "sat_firemod_springs_sm_zebra":"Accelerated Recoil System",
 "sat_firemod_trigger_pi_timir":"Match Grade Trigger",
 "sat_firemod_springs_sh_husky":"Recoil Springs",
 "sat_ammo_9x19_velocity_pi_atlas":"9mm Parabellum Overpressured",
 "sat_ammo_45cal_velocity_sm_orca":".45 Cal Overpressured",
 "sat_ammo_762n_fmj_sn_drake":"7.62 NATO FMJ",
 "sat_firemod_boltcarrier_sm_komodo":"Bolt Carrier Group",
 "sat_firemod_springs_sn_baltic":"Accelerated Recoil System",
 "sat_firemod_springs_pi_timir":"Pistol Recoil Spring",
 "sat_firemod_springs_ar_hawk":"Buffer Spring",
 "sat_firemod_springs_ar_condor":"Buffer Spring",
 "sat_firemod_bolt_sn_drake":"Light Bolt",
 "sat_bar_jump_sh_husky":"15\" Ghostline Barrel",
 "sat_bar_range_sh_husky":"18.7\" Magellan Dual Barrel",
 "sat_bar_mixbarrel_sh_husky":"16.1\" Proton Barrel",
 "sat_bar_highcal_sh_husky":"17.3\" Nero-Twin Barrel",
 "sat_stock_moverecovery_sh_corso":"SF-7X Stock",
 "sat_stock_quickdraw2_sh_corso":"M10 Light Grip",
 "sat_stock_sprintout_sh_corso":"Collapsible Stock",
 "sat_stock_quickdraw_sh_corso":"No Stock",
 "sat_stock_movespeed_sh_corso":"LW Skeleton Stock",
 "sat_bar_reload_sh_corso":"15.5\" Light Barrel",
 "sat_bar_recoil_sh_corso":"17\" Overload Barrel",
 "sat_bar_sprintout_sh_corso":"14\" Zephyr-R Barrel",
 "sat_thermal_holo01_dmr":"Solaris Holo-IR",
 "sat_mm_scanner01_sh":"Millimeter Scanner",
 "sat_mag_fastmag2_sm_komodo":"Bolt-Strike Speed Mag",
 "sat_mm_scanner01_ar":"Millimeter Scanner",
 "sat_fourx02_lmg":"PrismaTech Turbo 4x",
 "sat_holo02_ar":"EMT3 Holo Mk.2",
 "sat_varizoom01_lmg":"Greaves Ultra Zoom",
 "sat_hybrid01_ar":"EAM Dyad xL",
 "sat_reflex06_sh":"EAM xL Reflex",
 "sat_reflex02_ar":"Kepler-Pro Red Dot",
 "sat_rangefinder01_sn":"Circuit-Z Rangefinder",
 "sat_threex01_sn":"Greaves AccuSpot 3x",
 "sat_fourx02_dmr":"PrismaTech Turbo 4x",
 "sat_threex01_lmg":"Greaves AccuSpot 3x",
 "sat_thermal01_sn":"Bowen X-25 IR",
 "sat_twox01_dmr":"Redwell 30-S 2x",
 "sat_microreflex03_sh":"Lethal Tools ELO",
 "sat_dualzoom01_smg":"EAM Dual Zoom",
 "sat_hybrid02_smg":"VAS Duo Hybrid Sight",
 "sat_mm_scanner01_smg":"Millimeter Scanner",
 "sat_scope_snpr01_sn":"RistRauch 7x",
 "sat_reflex05_ar":"K&S Slim Reflex",
 "sat_reflex02_dmr":"Kepler-Pro Red Dot",
 "sat_reflex02_sh":"Kepler-Pro Red Dot",
 "sat_scope_pi":"Bowen Scout Scope",
 "sat_holo02_lmg":"EMT3 Holo Mk.2",
 "sat_rangefinder01_lmg":"Circuit-Z Rangefinder",
 "sat_microreflex01_sh":"LTI Mini",
 "sat_reflex03_smg":"LTI Reflex",
 "sat_microreflex03_ar":"Lethal Tools ELO",
 "sat_thermal_scope01_sn":"VAS Strix 6x Thermal",
 "sat_reflex05_smg":"K&S Slim Reflex",
 "sat_varizoom01_sn":"Greaves Ultra Zoom",
 "sat_reflex03_lmg":"LTI Reflex",
 "sat_twox01_smg":"Redwell 30-S 2x",
 "sat_microreflex04_pi":"EAM Micro Dot",
 "sat_thermal01_ar":"Bowen X-25 IR",
 "sat_fourx01_smg":"Kepler Ultra 4x",
 "sat_holo_range01_smg":"Kepler T-Range Holo",
 "sat_holo_range01_lmg":"Kepler T-Range Holo",
 "sat_holo_range01_sn":"Kepler T-Range Holo",
 "sat_holo02_sn":"EMT3 Holo Mk.2",
 "sat_thermal_scope01_ar":"VAS Strix 6x Thermal",
 "sat_threex01_sh":"Greaves AccuSpot 3x",
 "sat_microreflex01_ar":"LTI Mini",
 "sat_varizoom01_ar":"Greaves Ultra Zoom",
 "sat_microreflex02_sh":"VAS MicroFlex",
 "sat_holo01_smg":"PrismaTech Digital Holo",
 "sat_fourx02_sn":"PrismaTech Turbo 4x",
 "sat_hybrid02_dmr":"VAS Duo Hybrid Sight",
 "sat_reflex04_ar":"Greaves Red Dot",
 "sat_thermal_holo01_sh":"Solaris Holo-IR",
 "sat_mm_scanner01_sn":"Millimeter Scanner",
 "sat_reflex01_lmg":"VAS LED",
 "sat_microreflex03_dmr":"Lethal Tools ELO",
 "sat_microreflex02_ar":"VAS MicroFlex",
 "sat_hybrid02_sn":"VAS Duo Hybrid Sight",
 "sat_holo01_sh":"PrismaTech Digital Holo",
 "sat_fourx01_sn":"Kepler Ultra 4x",
 "sat_hybrid01_sn":"EAM Dyad xL",
 "sat_microreflex03_smg":"Lethal Tools ELO",
 "sat_reflex05_sh":"K&S Slim Reflex",
 "sat_reflex06_smg":"EAM xL Reflex",
 "sat_hybrid02_lmg":"VAS Duo Hybrid Sight",
 "sat_holo_range01_dmr":"Kepler T-Range Holo",
 "sat_thermal01_lmg":"Bowen X-25 IR",
 "sat_reflex01_sn":"VAS LED",
 "sat_holo02_dmr":"EMT3 Holo Mk.2",
 "sat_muzzle_sn_baltic":"DEFAULT",
 "sat_rec_la_polis":"Default Receiver",
 "sat_lnchrscope_la_polis":"Launcher Scope",
 "sat_dynamic_null_la_polis":"Dynamic Null Launcher",
 "sat_zm_la_polis":"ZM Attachment",
 "sat_zm_la_polis_pack":"ZM Attachment",
 "sat_killstreak_rec_rcxd_remote_v1":"Default Receiver",
 "sat_rec_rcxd_remote":"Default Receiver",
 "sat_ammo_556n":"Default Ammo",
 "sat_ammo_5x28":"Default Ammo",
 "sat_ammo_12g":"Default Ammo",
 "sat_ammo_45cal":"Default Ammo",
 "sat_ammo_9x19":"Default Ammo",
 "sat_pro_active_camo_stats_1":"Improved Electronics",
 "sat_pro_active_camo_mod_1":"Recloak",
 "sat_pro_combat_hologram_stats_1":"High Efficiency Battery",
 "sat_pro_combat_hologram_mod_1":"Proximity Sensor Flash",
 "sat_pro_cluster_grenade_mod_1":"Controllable Fuse",
 "sat_pro_cluster_grenade_stats_1":"Tighter Packing",
 "sat_pro_sensor_grenade_stats_1":"On Board AI",
 "sat_pro_sensor_grenade_mod_1":"Network Chip",
 "sat_pro_emp_grenade_stats_1":"On Board AI",
 "sat_pro_emp_grenade_mod_1":"9-Bang",
 "sat_pro_frag_stats_1":"High Density Explosive",
 "sat_pro_frag_mod_1":"Ultralight Metal",
 "t10_rec_rcxd_remote":"Default Receiver",
 "sat_underbarrel_sway_sn_baltic":"Zero-S Handguard",
 "sat_underbarrel_recoil_sn_baltic":"Neutralize-XR Handguard",
 "sat_underbarrel_mixunder_sn_baltic":"Advanced Step Handguard",
 "sat_underbarrel_mixunder2_sn_baltic":"LTI Enforcer Handgaurd",
 "sat_underbarrel_focus_sn_baltic":"Stalwart-5 Handgaurd",
 "sat_stock_mixstock_sn_baltic":"Exposed-73 Stock",
 "sat_stock_mixstock2_sn_baltic":"Lightshield Stock",
 "sat_stock_hipfiremove_sn_baltic":"LTI Collapsed Stock",
 "sat_stock_flinch_sn_baltic":"Lethal Absorb Stock",
 "sat_stock_adsmove_sn_baltic":"Padded Crush Stock",
 "sat_muzzle_suppressor_sn_baltic":"LTI Triad Suppressor",
 "sat_muzzle_comp_sn_baltic":"TriShot Compensator",
 "sat_muzzle_brake_sn_baltic":"Triptych Brake",
 "sat_mag_fastmag_sn_baltic":"PhantomV Fast Mag",
 "sat_mag_extmag_sn_baltic":"Overload Capacity Mag",
 "sat_mag_extmag2_sn_baltic":"Mammoth Stack Extended",
 "sat_laser_strelok_sn_baltic":"5mw Lockstep Laser",
 "sat_laser_mixlaser_sn_baltic":"1mW Instinct Laser Array",
 "sat_laser_mixlaser2_sn_baltic":"3mW Motion Strike Laser",
 "sat_laser_hipaccuracy_sn_baltic":"Convergence Box Laser",
 "sat_laser_focuslaser_sn_baltic":"2mw Adaptive Tactical Laser",
 "sat_grip_sprintout_sn_baltic":"XR-Omega Grip",
 "sat_grip_sprintout2_sn_baltic":"XR-Initialize Grip",
 "sat_grip_quickdraw_sn_baltic":"L.T. Sling Grip",
 "sat_grip_quickdraw2_sn_baltic":"Transit-Ion Grip",
 "sat_grip_mixgrip_sn_baltic":"L9 Vertigo Grip",
 "sat_bar_velocity_sn_baltic":"20\" Ion Trinity Barrel",
 "sat_bar_range_sn_baltic":"21\" LTI Infinity Barrel",
 "sat_bar_mixbarrel_sn_baltic":"17\" XR-Adapt Barrel",
 "sat_bar_jump_sn_baltic":"15\" Fringe Barrel",
 "sat_bar_highcal_sn_baltic":"19\" Revolution Barrel",
 "sat_reflex01_smg":"VAS LED",
 "sat_microreflex01_pi":"LTI Mini",
 "sat_fourx01_ar":"Kepler Ultra 4x",
 "sat_ammo_762n":"Default Ammo",
 "sat_underbarrel_sway_sm_komodo":"Fortify Handstop",
 "sat_underbarrel_sway_sh_corso":"Zero Shift Handstop",
 "sat_underbarrel_sway_lm_hades":"Ironhold Angled Grip",
 "sat_underbarrel_recoil_sm_komodo":"Lateral Precision Grip",
 "sat_underbarrel_recoil_sh_corso":"Force Stabilizer Handstop",
 "sat_underbarrel_recoil_lm_hades":"Bowen Sentry Foregrip",
 "sat_underbarrel_mixunder_sm_komodo":"EAM Lightpath Foregrip",
 "sat_underbarrel_mixunder_sh_corso":"Redwell Dash Handstop",
 "sat_underbarrel_mixunder_lm_hades":"Quickstep Foregrip",
 "sat_underbarrel_mixunder2_sm_komodo":"EAM Steady-90 Grip",
 "sat_underbarrel_mixunder2_sh_corso":"EAM Steady-90 Grip",
 "sat_underbarrel_mixunder2_lm_hades":"EAM Steady-90 Grip",
 "sat_underbarrel_focus_sm_komodo":"Respire Handstop",
 "sat_underbarrel_focus_lm_hades":"Enhance-32 Handstop",
 "sat_ub_crossbar_lm_hades":"Parallel Foregrip",
 "sat_stock_mixstock_sm_komodo":"Constrictor Pad",
 "sat_stock_mixstock_lm_hades":"Scatter Skeletal Stock",
 "sat_stock_mixstock2_sm_komodo":"Renegade Pad",
 "sat_stock_mixstock2_lm_hades":"SwiftGuard Stock",
 "sat_stock_hipfiremove_sm_komodo":"Serpent Pad",
 "sat_stock_hipfiremove_lm_hades":"Charon Light Stock",
 "sat_stock_flinch_sm_komodo":"RWL Stability Pad",
 "sat_stock_flinch_lm_hades":"Shock Shield Stock",
 "sat_stock_adsmove_sm_komodo":"Talos Pad",
 "sat_stock_adsmove_sh_corso":"R-54 Padded Stock",
 "sat_stock_adsmove_lm_hades":"Bowen Light Stock",
 "sat_muzzle_suppressor_sm_komodo":"Bowen 9mm Suppressor",
 "sat_muzzle_suppressor_sh_corso":"Redwell Agency Suppressor",
 "sat_muzzle_suppressor_lm_hades":"Greaves A-762",
 "sat_muzzle_mixmuzzle_sm_komodo":"Hawker Ported Comp",
 "sat_muzzle_mixmuzzle_lm_hades":"Titan-R 7.62 Compensator",
 "sat_muzzle_comp_sm_komodo":"H-9mm Precision Comp",
 "sat_muzzle_comp_lm_hades":"RL-7.62 Compensator",
 "sat_muzzle_choke_sh_corso":"Breacher Precision Choke",
 "sat_muzzle_choke2_sh_corso":"M10 CQB Choke",
 "sat_muzzle_brake_sm_komodo":"Hawker Stabilizer MK.II",
 "sat_muzzle_brake_sh_corso":"M10 Onyx Brake",
 "sat_muzzle_brake_lm_hades":"Bowen Modulator 7.62",
 "sat_mag_fastmag_sm_komodo":"Hawkline Fast Mag",
 "sat_mag_fastmag_lm_hades":"Swift Feed Fast Belt",
 "sat_mag_extmag_sm_komodo":"Strikeface Extended Clip",
 "sat_mag_extmag_sh_corso":"Extended Mag I",
 "sat_mag_extmag_lm_hades":"Gravepack Extended Belt",
 "sat_mag_extmag2_sm_komodo":"Zealot 50 Round Mag",
 "sat_mag_extmag2_lm_hades":"Payload Belt Extension",
 "sat_laser_strelok_sm_komodo":"VAS Precision Shift Laser",
 "sat_laser_strelok_sh_corso":"5mw Lockstep Laser",
 "sat_laser_strelok_lm_hades":"5mw Lockstep Laser",
 "sat_laser_mixlaser_sm_komodo":"LTI SwiftPoint Laser",
 "sat_laser_mixlaser_sh_corso":"1mW Instinct Laser Array",
 "sat_laser_mixlaser_lm_hades":"1mW Instinct Laser Array",
 "sat_laser_mixlaser2_sm_komodo":"EMT3 Agile Laser",
 "sat_laser_mixlaser2_sh_corso":"3mW Motion Strike Laser",
 "sat_laser_mixlaser2_lm_hades":"3mW Motion Strike Laser",
 "sat_laser_hipaccuracy_sm_komodo":"EAM ScatterLine Laser",
 "sat_laser_hipaccuracy_sh_corso":"Convergence Box Laser",
 "sat_laser_hipaccuracy_lm_hades":"Convergence Box Laser",
 "sat_laser_focuslaser_sm_komodo":"Redwell Tactical Laser",
 "sat_laser_focuslaser_sh_corso":"2mw Adaptive Tactical Laser",
 "sat_laser_focuslaser_lm_hades":"2mw Adaptive Tactical Laser",
 "sat_grip_sprintout_sm_komodo":"ReadiFlex Grip",
 "sat_grip_sprintout_lm_hades":"Bowen Thrust Grip",
 "sat_grip_sprintout2_sm_komodo":"Vice Grip",
 "sat_grip_sprintout2_lm_hades":"Fleet-G2 Grip",
 "sat_grip_quickdraw_sm_komodo":"Haste Ribbed Grip",
 "sat_grip_quickdraw_lm_hades":"Trailblaze Grip",
 "sat_grip_quickdraw2_sm_komodo":"Microdot Recovery Grip",
 "sat_grip_quickdraw2_lm_hades":"Hades Looper-X Grip",
 "sat_grip_mixgrip_sm_komodo":"EAM Pushback Grip",
 "sat_grip_mixgrip_lm_hades":"LTI Precision Grip",
 "sat_bar_velocity_lm_hades":"18.5\" Mach-78 Barrel",
 "sat_bar_range_sm_komodo":"13\" RL-Genesys Barrel",
 "sat_bar_range_sh_corso":"17.4\" Redwell-5K Barrel",
 "sat_bar_range_lm_hades":"17\" Bowen Moon Barrel",
 "sat_bar_mixbarrel_sm_komodo":"9.5\" Synthesis Barrel",
 "sat_bar_mixbarrel_sh_corso":"19.8\" Bull Barrel",
 "sat_bar_mixbarrel_lm_hades":"20\" Titan Hybrid Barrel",
 "sat_bar_jump_sm_komodo":"9\" Heron Barrel",
 "sat_bar_jump_lm_hades":"15\" Skylance Barrel",
 "sat_bar_highcal_sm_komodo":"10\" Razor Impact Barrel",
 "sat_bar_highcal_lm_hades":"22\" Impulse HB-762 Barrel",
 "sat_underbarrel_sway_sm_orca":"Fortify Handstop",
 "sat_underbarrel_sway_dm_scotia":"Ironhold Angled Grip",
 "sat_underbarrel_recoil_sm_orca":"Lateral Precision Grip",
 "sat_underbarrel_recoil_dm_scotia":"Force Stabilizer Handstop",
 "sat_underbarrel_mixunder_sm_orca":"EAM Lightpath Foregrip",
 "sat_underbarrel_mixunder_dm_scotia":"Quickstep Foregrip",
 "sat_underbarrel_mixunder2_sm_orca":"Flowguard Foregrip",
 "sat_underbarrel_mixunder2_dm_scotia":"Envoy Foregrip",
 "sat_underbarrel_focus_sm_orca":"Respire Handstop",
 "sat_underbarrel_focus_dm_scotia":"Enhance-32 Handstop",
 "sat_stock_mixstock_sh_husky":"Scatterproof Stock",
 "sat_stock_mixstock2_sm_orca":"SKE-02 Stock",
 "sat_stock_mixstock2_sh_husky":"EAM Stonewall Stock",
 "sat_stock_mixstock2_dm_scotia":"Gridlock Stock",
 "sat_stock_hipfiremove_sm_orca":"Collapsible Stock",
 "sat_stock_hipfiremove_sh_husky":"Greaves Stalker Stock",
 "sat_stock_hipfiremove_dm_scotia":"VAS Barrage-01 Stock",
 "sat_stock_flinch_sm_orca":"VAS Interlock Stock",
 "sat_stock_flinch_sh_husky":"Bowen Defender Stock",
 "sat_stock_flinch_dm_scotia":"K&S Impact Stock",
 "sat_stock_akimbo_pi_timir":"Akimbo Jäger 45",
 "sat_stock_akimbo_pi_atlas":"Akimbo Coda 9",
 "sat_stock_adsmove_sm_orca":"Ventral Stock",
 "sat_stock_adsmove_sh_husky":"Extraction Stock",
 "sat_stock_adsmove_dm_scotia":"Swiftline Stock",
 "sat_muzzle_suppressor_sm_orca":"Bowen .45 Suppressor",
 "sat_muzzle_suppressor_sh_husky":"Dual Clone Suppressor",
 "sat_muzzle_suppressor_pi_timir":"Jäger Roar Suppressor",
 "sat_muzzle_suppressor_pi_atlas":"Bowen 9mm Suppressor",
 "sat_muzzle_suppressor_dm_scotia":"VAS 5.56 Suppressor",
 "sat_muzzle_mixmuzzle_sm_orca":"Hawker Hybrid .45",
 "sat_muzzle_mixmuzzle_pi_timir":"Hawker Ported Comp",
 "sat_muzzle_mixmuzzle_pi_atlas":"Hawker Ported Comp",
 "sat_muzzle_mixmuzzle_dm_scotia":"Titan-R 5.56 Compensator",
 "sat_muzzle_comp_sm_orca":"Hawker Series 45",
 "sat_muzzle_comp_pi_timir":"H-45 Precision Comp",
 "sat_muzzle_comp_pi_atlas":"H-9mm Precision Comp",
 "sat_muzzle_comp_dm_scotia":"Redwell 5.56 Compensator",
 "sat_muzzle_choke_sh_husky":"Echo Modified Choke",
 "sat_muzzle_choke2_sh_husky":"Dual-Crown Echo Choke",
 "sat_muzzle_brake_sm_orca":"Hawker Stabilizer MK.II",
 "sat_muzzle_brake_sh_husky":"Dual Dampener",
 "sat_muzzle_brake_pi_timir":"Ported-45 Brake",
 "sat_muzzle_brake_pi_atlas":"Hawker-9 Brake",
 "sat_muzzle_brake_dm_scotia":"RL-5.56 Brake",
 "sat_mag_flipmag_sm_orca":"Fraternity Flip Mag",
 "sat_mag_flipmag_dm_scotia":"Echo Reverse Flip Mag",
 "sat_mag_fastmag_sm_orca":"Breakpoint Fast Mag",
 "sat_mag_fastmag_sh_husky":"VAS BravoTap Dum",
 "sat_mag_fastmag_pi_timir":"Stryder-Snap Speed Clip",
 "sat_mag_fastmag_pi_atlas":"NanoFeed Fast Mag",
 "sat_mag_fastmag_dm_scotia":"Blink-Chamber Fast Clip",
 "sat_mag_extmag_sm_orca":"Torch 40 Round Mag",
 "sat_mag_extmag_sh_husky":"Greaves Fortrex Drum",
 "sat_mag_extmag_pi_timir":"Warpath Capacity Mag",
 "sat_mag_extmag_pi_atlas":"Hellgate Stick Mag",
 "sat_mag_extmag_dm_scotia":"Sentinel Extended Mag",
 "sat_mag_extmag2_sm_orca":"Forward Breach Mag",
 "sat_mag_extmag2_pi_timir":"Goliath-X Extended+",
 "sat_mag_extmag2_dm_scotia":"Redline 52 Round Drum",
 "sat_laser_strelok_sm_orca":"VAS Precision Shift Laser",
 "sat_laser_strelok_sh_husky":"5mw Lockstep Laser",
 "sat_laser_strelok_pi_timir":"Jäger Rapid Zero-X Laser",
 "sat_laser_strelok_pi_atlas":"4mW Snap Laser",
 "sat_laser_strelok_dm_scotia":"5mw Lockstep Laser",
 "sat_laser_mixlaser_sm_orca":"LTI SwiftPoint Laser",
 "sat_laser_mixlaser_sh_husky":"1mW Instinct Laser Array",
 "sat_laser_mixlaser_pi_timir":"Rapid Sight Motion Laser",
 "sat_laser_mixlaser_pi_atlas":"1mW Pulse Laser",
 "sat_laser_mixlaser_dm_scotia":"1mW Instinct Laser Array",
 "sat_laser_mixlaser2_sm_orca":"EMT3 Agile Laser",
 "sat_laser_mixlaser2_sh_husky":"3mW Motion Strike Laser",
 "sat_laser_mixlaser2_pi_timir":"AirGlide Target Laser",
 "sat_laser_mixlaser2_pi_atlas":"K-Flash Target Laser",
 "sat_laser_mixlaser2_dm_scotia":"3mW Motion Strike Laser",
 "sat_laser_hipaccuracy_sm_orca":"EAM ScatterLine Laser",
 "sat_laser_hipaccuracy_sh_husky":"Convergence Box Laser",
 "sat_laser_hipaccuracy_pi_timir":"Vector Sync Laser",
 "sat_laser_hipaccuracy_pi_atlas":"2mW Pinpoint Pistol Laser",
 "sat_laser_hipaccuracy_dm_scotia":"Convergence Box Laser",
 "sat_laser_focuslaser_sm_orca":"Redwell Tactical Laser",
 "sat_laser_focuslaser_sh_husky":"2mw Adaptive Tactical Laser",
 "sat_laser_focuslaser_pi_timir":"Jäger Tactical Laser",
 "sat_laser_focuslaser_pi_atlas":"Tactical Flex Laser",
 "sat_laser_focuslaser_dm_scotia":"2mw Adaptive Tactical Laser",
 "sat_grip_sprintout_sm_orca":"Lennox Grip",
 "sat_grip_sprintout_sh_husky":"EAM Ignition Grip",
 "sat_grip_sprintout_pi_timir":"Dash-L Grip",
 "sat_grip_sprintout_pi_atlas":"Pincer Grip",
 "sat_grip_sprintout_dm_scotia":"Rush-99 Grip",
 "sat_grip_sprintout2_sm_orca":"Bounty Grip",
 "sat_grip_sprintout2_sh_husky":"Axel Control Grip",
 "sat_grip_sprintout2_pi_timir":"Ranger Lite Grip",
 "sat_grip_sprintout2_pi_atlas":"Muse Grip",
 "sat_grip_sprintout2_dm_scotia":"G7-Launch Grip",
 "sat_grip_quickdraw_sm_orca":"Excess Grip",
 "sat_grip_quickdraw_sh_husky":"Phantom-17 Grip",
 "sat_grip_quickdraw_pi_timir":"Intercept Grip",
 "sat_grip_quickdraw_pi_atlas":"Express Grip",
 "sat_grip_quickdraw_dm_scotia":"Instinct Grip",
 "sat_grip_quickdraw2_sm_orca":"Eruption Grip",
 "sat_grip_quickdraw2_sh_husky":"Traverse Grip",
 "sat_grip_quickdraw2_pi_timir":"VX-Shift Grip",
 "sat_grip_quickdraw2_pi_atlas":"ST3-Gloria Grip",
 "sat_grip_quickdraw2_dm_scotia":"K&S Raze Grip",
 "sat_grip_mixgrip_sm_orca":"Skeletonized Grip",
 "sat_grip_mixgrip_sh_husky":"Harbinger Grip",
 "sat_grip_mixgrip_pi_timir":"GL-3N Grip",
 "sat_grip_mixgrip_pi_atlas":"Terra-1X Grip",
 "sat_grip_mixgrip_dm_scotia":"Schmidt Trapper Grip",
 "sat_bar_velocity_sm_orca":"11\" Rauch 6L-R Barrel",
 "sat_bar_velocity_pi_timir":"8\" Warp-45 Barrel",
 "sat_bar_velocity_pi_atlas":"5.6\" Banisher Barrel",
 "sat_bar_velocity_dm_scotia":"18\" Ionic-8 Barrel",
 "sat_bar_range_sm_orca":"12\" Vienna Barrel",
 "sat_bar_range_pi_timir":"8.7\" EAM Voyager Barrel",
 "sat_bar_range_pi_atlas":"6.3\" Greaves Halberd Barrel",
 "sat_bar_range_dm_scotia":"23\" Barrier Barrel",
 "sat_bar_mixbarrel_sm_orca":"10.5\" Greaves Whiptail Barrel",
 "sat_bar_mixbarrel_pi_timir":"7.1\" Hawker Ion Barrel",
 "sat_bar_mixbarrel_pi_atlas":"5\" LTI Epsilon-1 Barrel",
 "sat_bar_mixbarrel_dm_scotia":"21\" Frontline Barrel",
 "sat_bar_jump_sm_orca":"9\" Basilisk Barrel",
 "sat_bar_jump_pi_timir":"6.3\" Elevation Barrel",
 "sat_bar_jump_pi_atlas":"4.1\" Paragon Barrel",
 "sat_bar_jump_dm_scotia":"15\" Ascend-KS Barrel",
 "sat_bar_highcal_sm_orca":"10.5\" Slim-Mod Barrel",
 "sat_bar_highcal_pi_atlas":"4.9\" Omen Barrel",
 "sat_bar_highcal_dm_scotia":"16.5\" Deadeye Barrel",
 "sat_underbarrel_sway_ar_hawk":"Ironhold Angled Grip",
 "sat_underbarrel_sway_ar_eagle":"Sentry Pro Handstop",
 "sat_underbarrel_sway_ar_condor":"Sentry Pro Handstop",
 "sat_underbarrel_recoil_ar_hawk":"Axis Shift Vertical Foregrip",
 "sat_underbarrel_recoil_ar_eagle":"Lateral Precision Grip",
 "sat_underbarrel_recoil_ar_condor":"Lateral Precision Grip",
 "sat_underbarrel_mixunder_ar_hawk":"Quickstep Foregrip",
 "sat_underbarrel_mixunder_ar_eagle":"Quickstep Foregrip",
 "sat_underbarrel_mixunder_ar_condor":"Quickstep Foregrip",
 "sat_underbarrel_mixunder2_ar_hawk":"EAM Steady-90 Grip",
 "sat_underbarrel_mixunder2_ar_eagle":"EAM Steady-90 Grip",
 "sat_underbarrel_mixunder2_ar_condor":"EAM Steady-90 Grip",
 "sat_underbarrel_focus_ar_hawk":"Enhance-32 Handstop",
 "sat_underbarrel_focus_ar_eagle":"Enhance-32 Handstop",
 "sat_underbarrel_focus_ar_condor":"Enhance-32 Handstop",
 "sat_ub_gl_std_ar_hawk":"Launcher - Standard",
 "sat_ub_gl_std_ar_eagle":"Launcher - Standard",
 "sat_ub_gl_std_ar_condor":"Launcher - Standard",
 "sat_ub_gl_smoke_ar_hawk":"Launcher - Smoke",
 "sat_ub_gl_smoke_ar_eagle":"Launcher - Smoke",
 "sat_ub_gl_smoke_ar_condor":"Launcher - Smoke",
 "sat_ub_gl_he_ar_hawk":"Launcher - High Explosive",
 "sat_ub_gl_he_ar_eagle":"Launcher - High Explosive",
 "sat_ub_gl_he_ar_condor":"Launcher - High Explosive",
 "sat_ub_gl_dc_ar_hawk":"Launcher - Drill Charge",
 "sat_ub_gl_dc_ar_eagle":"Launcher - Drill Charge",
 "sat_ub_gl_dc_ar_condor":"Launcher - Drill Charge",
 "sat_stock_mixstock_ar_hawk":"Ultralight Tactical Stock",
 "sat_stock_mixstock_ar_eagle":"Skeletal Stock",
 "sat_stock_mixstock_ar_condor":"Pathfinder-Skel Stock",
 "sat_stock_mixstock2_ar_hawk":"Intervention Stock",
 "sat_stock_mixstock2_ar_eagle":"VAS TH-09 Stock",
 "sat_stock_mixstock2_ar_condor":"EAM Blitzfire Stock",
 "sat_stock_hipfiremove_ar_hawk":"Telescopic Stock",
 "sat_stock_hipfiremove_ar_eagle":"Greaves Covenant Stock",
 "sat_stock_hipfiremove_ar_condor":"Swift-B Guard Stock",
 "sat_stock_flinch_ar_hawk":"Bowen Linchpin Stock",
 "sat_stock_flinch_ar_eagle":"Winch Stock",
 "sat_stock_adsmove_ar_hawk":"Wander-3V Stock",
 "sat_stock_adsmove_ar_eagle":"Gait-Lux Stock",
 "sat_stock_adsmove_ar_condor":"Vagrant-93 Stock",
 "sat_muzzle_suppressor_ar_hawk":"VAS 5.56 Suppressor",
 "sat_muzzle_suppressor_ar_eagle":"Greaves Ti-762",
 "sat_muzzle_suppressor_ar_condor":"K&S Stalker 57-X",
 "sat_muzzle_mixmuzzle_ar_hawk":"Titan-R 5.56 Compensator",
 "sat_muzzle_mixmuzzle_ar_eagle":"Titan-R 7.62 Compensator",
 "sat_muzzle_mixmuzzle_ar_condor":"Kühn Ported Comp",
 "sat_muzzle_comp_ar_hawk":"Redwell 5.56 Compensator",
 "sat_muzzle_comp_ar_eagle":"Redwell-90 Compensator",
 "sat_muzzle_comp_ar_condor":"K&S Compensator",
 "sat_muzzle_brake_ar_hawk":"RL-5.56 Brake",
 "sat_muzzle_brake_ar_eagle":"Redwell 7.62 Brake",
 "sat_muzzle_brake_ar_condor":"K&S Brake-2B",
 "sat_mag_flipmag_ar_hawk":"Backline Flip Mag",
 "sat_mag_flipmag_ar_eagle":"TwinPack Flip Mags",
 "sat_mag_flipmag_ar_condor":"Snap Switch Magazines",
 "sat_mag_fastmag_ar_hawk":"Nomad Reserve Fast Mag",
 "sat_mag_fastmag_ar_condor":"ReconClip Speed Mag",
 "sat_mag_extmag_ar_hawk":"Mayday Extended Mag",
 "sat_mag_extmag_ar_eagle":"Vault Extended Mag",
 "sat_mag_extmag_ar_condor":"Vulcan Reach Extension",
 "sat_mag_extmag2_ar_hawk":"Bowen Bulwark Mag",
 "sat_mag_extmag2_ar_eagle":"Rhodes Drum Mag",
 "sat_mag_extmag2_ar_condor":"Barrage 50 Round Mag",
 "sat_laser_strelok_ar_hawk":"5mw Lockstep Laser",
 "sat_laser_strelok_ar_eagle":"5mw Lockstep Laser",
 "sat_laser_strelok_ar_condor":"VAS Precision Shift Laser",
 "sat_laser_mixlaser_ar_hawk":"1mW Instinct Laser Array",
 "sat_laser_mixlaser_ar_eagle":"1mW Instinct Laser Array",
 "sat_laser_mixlaser_ar_condor":"LTI SwiftPoint Laser",
 "sat_laser_mixlaser2_ar_hawk":"3mW Motion Strike Laser",
 "sat_laser_mixlaser2_ar_eagle":"3mW Motion Strike Laser",
 "sat_laser_mixlaser2_ar_condor":"EMT3 Agile Laser",
 "sat_laser_hipaccuracy_ar_hawk":"Convergence Box Laser",
 "sat_laser_hipaccuracy_ar_eagle":"Convergence Box Laser",
 "sat_laser_hipaccuracy_ar_condor":"EAM ScatterLine Laser",
 "sat_laser_focuslaser_ar_hawk":"Adaptive Tactical Laser",
 "sat_laser_focuslaser_ar_eagle":"2mw Adaptive Tactical Laser",
 "sat_laser_focuslaser_ar_condor":"Redwell Tactical Laser",
 "sat_grip_sprintout_ar_hawk":"Contour Grip",
 "sat_grip_sprintout_ar_eagle":"Bell-H81 Grip",
 "sat_grip_sprintout_ar_condor":"EAM Dashfire Grip",
 "sat_grip_sprintout2_ar_hawk":"Caravan-H2 Grip",
 "sat_grip_sprintout2_ar_eagle":"Fissure Grip",
 "sat_grip_sprintout2_ar_condor":"Kinetix-Mk 1 Grip",
 "sat_grip_quickdraw_ar_hawk":"Peregrine Grip",
 "sat_grip_quickdraw_ar_eagle":"Celerity Grip",
 "sat_grip_quickdraw_ar_condor":"Rapid-Lock Grip",
 "sat_grip_quickdraw2_ar_hawk":"Hexcut Grip",
 "sat_grip_quickdraw2_ar_eagle":"Aria Assail Grip",
 "sat_grip_quickdraw2_ar_condor":"DiveEdge-7 Grip",
 "sat_grip_mixgrip_ar_hawk":"Contraband Grip",
 "sat_grip_mixgrip_ar_eagle":"Virgil-XI Grip",
 "sat_grip_mixgrip_ar_condor":"Accordance Grip",
 "sat_bar_velocity_ar_hawk":"20\" Delta-F2 Barrel",
 "sat_bar_velocity_ar_eagle":"18\" Sterling-G Barrel",
 "sat_bar_velocity_ar_condor":"19.4\" Stimulus Barrel",
 "sat_bar_range_ar_hawk":"18\" Bowen Watchtower Barrel",
 "sat_bar_range_ar_eagle":"20\" Imperial Barrel",
 "sat_bar_range_ar_condor":"23.5\" Longbow Barrel",
 "sat_bar_mixbarrel_ar_hawk":"16.5\" Fusion Barrel",
 "sat_bar_mixbarrel_ar_eagle":"18\" Rift-M7 Barrel",
 "sat_bar_mixbarrel_ar_condor":"21\" DF-3 Merge Barrel",
 "sat_bar_jump_ar_hawk":"15\" Mirage Light Barrel",
 "sat_bar_jump_ar_eagle":"15\" Wraith Barrel",
 "sat_bar_jump_ar_condor":"14.5\" E7-Cuff Barrel",
 "sat_bar_highcal_ar_hawk":"16\" Reticulated Barrel",
 "sat_bar_highcal_ar_eagle":"17\" Greaves Scourge Barrel",
 "sat_bar_highcal_ar_condor":"25\" EAM Heavy Barrel",
 "t10_equip_monkey_bomb_rec_deadops":"NA",
 "t10_equip_blackhole_bomb_rec_parasite":"NA",
 "t10_equip_monkey_bomb_rec":"NA",
 "t10_equip_blackhole_bomb_rec":"NA",
 "sat_stock_mixstock_sm_zebra":"Converge Tactical Stock",
 "sat_stock_mixstock2_sm_zebra":"Defiant-45 Skeletal Stock",
 "sat_stock_hipfiremove_sm_zebra":"EAM Heritage Stock",
 "sat_stock_flinch_sm_zebra":"Endurance LD-6 Stock",
 "sat_stock_adsmove_sm_zebra":"Serval Q-Step Stock",
 "sat_muzzle_suppressor_sm_zebra":"Bowen .45 Suppressor",
 "sat_muzzle_mixmuzzle_sm_zebra":"Hawker Hybrid .45",
 "sat_muzzle_comp_sm_zebra":"Hawker Series 45",
 "sat_muzzle_brake_sm_zebra":"Hawker Stabilizer MK.II",
 "sat_mag_fastmag_sm_zebra":"FrontGate Fast Loader",
 "sat_mag_extmag_sm_zebra":"Gator Extended Mag",
 "sat_mag_extmag2_sm_zebra":"Lockjaw Extended Mag",
 "sat_laser_strelok_sm_zebra":"VAS Precision Shift Laser",
 "sat_laser_mixlaser_sm_zebra":"LTI SwiftPoint Laser",
 "sat_laser_hipaccuracy_sm_zebra":"EAM ScatterLine Laser",
 "sat_laser_focuslaser_sm_zebra":"Redwell Tactical Laser",
 "sat_grip_sprintout_sm_zebra":"Helix-Tac Grip",
 "sat_grip_sprintout2_sm_zebra":"Vantix-8 Grip",
 "sat_grip_quickdraw_sm_zebra":"QuikArm Grip",
 "sat_grip_quickdraw2_sm_zebra":"Herald-Z1 Grip",
 "sat_grip_mixgrip_sm_zebra":"Delta Axis Grip",
 "sat_bar_velocity_sm_zebra":"18\" Jetstream Barrel",
 "sat_bar_range_sm_zebra":"19\" Horizon Fluted Barrel",
 "sat_bar_mixbarrel_sm_zebra":"14\" Verse Barrel",
 "sat_bar_jump_sm_zebra":"12\" Cloud Barrel",
 "sat_bar_highcal_sm_zebra":"16.5\" Predator Barrel",
 "sat_underbarrel_sway_sn_drake":"Stetig-C Handguard",
 "sat_underbarrel_recoil_sn_drake":"AxisPro Handgaurd",
 "sat_underbarrel_mixunder_sn_drake":"Kinetic Lock Handguard",
 "sat_underbarrel_mixunder2_sn_drake":"Breacher Hanguard",
 "sat_stock_mixstock_sn_drake":"Stronghold Stock Pad",
 "sat_stock_mixstock2_sn_drake":"Outpost Raider Pad",
 "sat_stock_hipfiremove_sn_drake":"Contra Light Pad",
 "sat_stock_flinch_sn_drake":"Stabil Heavy Pad",
 "sat_stock_adsmove_sn_drake":"RistRauch Breach Pad",
 "sat_muzzle_suppressor_sn_drake":"Greaves A-762",
 "sat_muzzle_mixmuzzle_sn_drake":"Titan-R 7.62 Compensator",
 "sat_muzzle_comp_sn_drake":"RL-7.62 Compensator",
 "sat_muzzle_brake_sn_drake":"VS-762 Brake",
 "sat_mag_fastmag_sn_drake":"DashLine Speed Mag",
 "sat_mag_extmag_sn_drake":"Wyvern Extend-Z Mag",
 "sat_mag_extmag2_sn_drake":"VS-R Extended II",
 "sat_laser_strelok_sn_drake":"5mw Lockstep Laser",
 "sat_laser_mixlaser_sn_drake":"1mW Instinct Laser Array",
 "sat_laser_mixlaser2_sn_drake":"3mW Motion Strike Laser",
 "sat_laser_hipaccuracy_sn_drake":"Convergence Box Laser",
 "sat_laser_focuslaser_sn_drake":"Adaptive Tactical Laser",
 "sat_grip_sprintout_sn_drake":"R-2-Laúfen Grip",
 "sat_grip_sprintout2_sn_drake":"Skeletal Grip",
 "sat_grip_quickdraw_sn_drake":"R-1 Shelf Grip",
 "sat_grip_quickdraw2_sn_drake":"Kinesis Grip",
 "sat_grip_mixgrip_sn_drake":"VS Poise Grip",
 "sat_bar_velocity_sn_drake":"23\" G-Force Barrel",
 "sat_bar_range_sn_drake":"24.9\" Domain Barrel",
 "sat_bar_mixbarrel_sn_drake":"21\" Engage-R Barrel",
 "sat_bar_jump_sn_drake":"17\" RistRauch Nimbus Barrel",
 "sat_bar_highcal_sn_drake":"19.3\" Tack Driver Barrel",
 "sat_zm_sh_corso_pack":"ZM Attachment",
 "sat_zm_sh_corso":"ZM Attachment",
 "sat_zm_pi_timir_pack":"ZM Attachment",
 "sat_zm_pi_timir":"ZM Attachment",
 "sat_tube_sh_corso":"DEFAULT",
 "sat_trigger_pi_timir":"DEFAULT",
 "sat_stock_sh_corso":"Default Stock",
 "sat_rec_sh_corso":"Default Receiver",
 "sat_rec_pi_timir":"Default Receiver",
 "sat_mag_pi_timir":"Default Magazine",
 "sat_ironsights_sh_corso":"Default Iron Sights",
 "sat_ironsights_pi_timir":"Default Iron Sights",
 "sat_guard_sh_corso":"DEFAULT",
 "sat_grip_sh_corso":"Default Grip",
 "sat_grip_pi_timir":"Default Grip",
 "sat_bar_sh_corso":"Default Barrel",
 "sat_bar_pi_timir":"Default Barrel",
 "sat_zm_sn_baltic_pack":"ZM Attachment",
 "sat_zm_sn_baltic":"ZM Attachment",
 "sat_zm_lm_hades_pack":"ZM Attachment",
 "sat_zm_lm_hades":"ZM Attachment",
 "sat_underbarrel_sn_baltic":"Default Underbarrel",
 "sat_stock_sn_baltic":"Default Stock",
 "sat_stock_lm_hades":"Default Stock",
 "sat_scopes_sn_baltic":"Default Scope",
 "sat_rec_sn_baltic":"Default Receiver",
 "sat_rec_lm_hades":"Default Receiver",
 "sat_mag_sn_baltic":"Default Magazine",
 "sat_ironsights_lm_hades":"Default Iron Sights",
 "sat_grip_sn_baltic":"Default Grip",
 "sat_grip_lm_hades":"Default Grip",
 "sat_bolt_sn_baltic":"Default Bolt",
 "sat_belt_lm_hades":"Default Belt",
 "sat_bar_sn_baltic":"Default Barrel",
 "sat_bar_lm_hades":"Default Barrel",
 "sat_zm_dm_scotia_pack":"ZM Attachment",
 "sat_zm_dm_scotia":"ZM Attachment",
 "sat_stock_dm_scotia":"Default Stock",
 "sat_selectsemi_dm_scotia":"Fire Select - Semi-Auto",
 "sat_rec_dm_scotia":"Default Receiver",
 "sat_mag_dm_scotia":"Default Magazine",
 "sat_ironsights_dm_scotia":"Default Iron Sights",
 "sat_grip_dm_scotia":"Default Grip",
 "sat_bar_dm_scotia":"Default Barrel",
 "sat_zm_sm_orca_pack":"ZM Attachment",
 "sat_zm_sm_orca":"ZM Attachment",
 "sat_zm_sm_komodo_pack":"ZM Attachment",
 "sat_zm_sm_komodo":"ZM Attachment",
 "sat_stock_sm_orca":"Default Stock",
 "sat_stock_sm_komodo":"Default Stock",
 "sat_selectsemi_sm_orca":"Fire Select - Semi-Auto",
 "sat_selectsemi_sm_komodo":"Fire Select - Semi-Auto",
 "sat_rec_sm_orca":"Default Receiver",
 "sat_rec_sm_komodo":"Default Receiver",
 "sat_mag_sm_orca":"Default Magazine",
 "sat_mag_sm_komodo":"Default Magazine",
 "sat_ironsights_sm_orca":"Default Iron Sights",
 "sat_ironsights_sm_komodo":"Default Iron Sights",
 "sat_grip_sm_orca":"Default Grip",
 "sat_grip_sm_komodo":"Default Grip",
 "sat_bar_sm_orca":"Default Barrel",
 "sat_bar_sm_komodo":"Default Barrel",
 "sat_zm_ar_eagle_pack":"ZM Attachment",
 "sat_zm_ar_eagle":"ZM Attachment",
 "sat_zm_ar_condor_pack":"ZM Attachment",
 "sat_zm_ar_condor":"ZM Attachment",
 "sat_stock_ar_eagle":"Default Stock",
 "sat_stock_ar_condor":"Default Stock",
 "sat_selectsemi_ar_eagle":"Fire Select - Semi-Auto",
 "sat_selectsemi_ar_condor":"Fire Select - Semi-Auto",
 "sat_rec_ar_eagle":"Default Receiver",
 "sat_rec_ar_condor":"Default Receiver",
 "sat_mag_ar_eagle":"Default Magazine",
 "sat_mag_ar_condor":"Default Magazine",
 "sat_ironsights_ar_eagle":"Default Iron Sights",
 "sat_ironsights_ar_condor":"Default Iron Sights",
 "sat_grip_ar_eagle":"Default Grip",
 "sat_grip_ar_condor":"Default Grip",
 "sat_bar_ar_eagle":"Default Barrel",
 "sat_bar_ar_condor":"Default Barrel",
 "sat_zm_ar_hawk_pack":"ZM Attachment",
 "sat_zm_ar_hawk":"ZM Attachment",
 "sat_stock_ar_hawk":"Default Stock",
 "sat_selectsemi_ar_hawk":"Fire Select - Semi-Auto",
 "sat_mag_ar_hawk":"Default Magazine",
 "sat_ironsight_ar_hawk":"Default Iron Sights",
 "sat_grip_ar_hawk":"Default Grip",
 "sat_bar_ar_hawk":"Default Barrel",
 "sat_zm_sn_drake_pack":"ZM Attachment",
 "sat_zm_sn_drake":"ZM Attachment",
 "sat_zm_sh_husky_pack":"ZM Attachment",
 "sat_zm_sh_husky":"ZM Attachment",
 "sat_zm_pi_atlas_pack":"ZM Attachment",
 "sat_zm_pi_atlas":"ZM Attachment",
 "sat_underbarrel_sn_drake":"Default Underbarrel",
 "sat_stock_sn_drake":"Default Stock",
 "sat_stock_sh_husky":"Default Stock",
 "sat_scope_sn_drake":"Default Scope",
 "sat_rec_sn_drake":"Default Receiver",
 "sat_rec_sh_husky":"Default Receiver",
 "sat_mag_sn_drake":"Default Magazine",
 "sat_mag_sh_husky":"Default Magazine",
 "sat_mag_pi_atlas":"Default Magazine",
 "sat_ironsights_sm_zebra":"Default Iron Sights",
 "sat_ironsights_sh_husky":"Default Iron Sights",
 "sat_ironsights_pi_atlas":"Default Iron Sights",
 "sat_grip_sn_drake":"Default Grip",
 "sat_grip_sh_husky":"Default Grip",
 "sat_grip_pi_atlas":"Default Grip",
 "sat_bolt_sn_drake":"Default Bolt",
 "sat_bar_sn_drake":"Default Barrel",
 "sat_bar_sh_husky":"Default Barrel",
 "sat_bar_pi_atlas":"Default Barrel",
 "sat_zm_sm_zebra_pack":"ZM Attachment",
 "sat_zm_sm_zebra":"ZM Attachment",
 "sat_selectsemi_sm_zebra":"Fire Select - Semi-Auto",
 "sat_rec_sm_zebra":"Default Receiver",
 "sat_mag_sm_zebra":"Default Magazine",
 "sat_grip_sm_zebra":"Default Grip",
 "sat_bar_sm_zebra":"Default Barrel",
 "sat_scope_ks_sniper_briefcase":"Default Scope",
 "sat_rec_ks_sniper_briefcase":"Default Receiver",
 "sat_mag_ks_sniper_briefcase":"Default Magazine",
 "sat_bar_ks_sniper_briefcase":"Default Barrel",
 "t10_mag_raygun":"Default Magazine",
 "t10_bar_raygun":"Default Barrel",
 "t10_zm_raygunmark2_pack":"ZM Attachment",
 "t10_zm_raygunmark2":"ZM Attachment",
 "t10_zm_raygun_pack":"ZM Attachment",
 "t10_zm_raygun":"ZM Attachment",
 "t10_bar_jump_ar_coslo":"Short Barrel",
 "t10_threex01_ar":"Willis 3x",
 "t10_rec_raygunmark2":"Default Receiver",
 "t10_rec_raygun":"Default Receiver",
 "t10_reddot03_ar_tall":"Otero Red Dot",
 "t10_me_knife":"Default Receiver",
 "t10_microreflex04_ar_tall":"Merlin Mini",
 "t10_microreflex04_ar":"Merlin Mini",
 "t10_reflex01_ar_tall":"PrismaTech Reflex",
 "t10_reflex01_ar":"PrismaTech Reflex",
 "t10_reddot03_ar":"Otero Red Dot",
 "t10_ammo_556n_velocity_ar_coslo723":"5.56 NATO Overpressured",
 "t10_ammo_556n_fmj_ar_coslo723":"5.56 NATO FMJ",
 "t10_ub_gl_std_ar_coslo723":"Launcher - Standard",
 "t10_ub_gl_smoke_ar_coslo723":"Launcher - Smoke",
 "t10_ub_gl_he_ar_coslo723":"Launcher - High Explosive",
 "t10_ub_gl_dc_ar_coslo723":"Launcher - Drill Charge",
 "t10_mags_flip_ar_coslo":"Flip Mag",
 "t10_firemod_boltcarrier_ar_coslo723":"Rapid Fire",
 "t10_firemod_springs_ar_coslo723":"Recoil Springs",
 "jup_jp01_ar_golf36_amps":"Aftermarket Category",
 "t10_ammo_762n":"7.62 NATO",
 "t10_lasers_mixlaser_ar_coslo":"Fast Motion Laser",
 "t10_lasers_mixlaser2_ar_coslo":"Target Laser",
 "t10_lasers_strelok_ar_coslo":"Strelok Laser",
 "t10_lasers_focuslaser_ar_coslo":"Tactical Laser",
 "t10_grips_sprintout2_ar_coslo":"CQB Grip",
 "t10_grips_quickdraw2_ar_coslo":"Ergonomic Grip",
 "t10_ammo_556n":"NA",
 "t10_underbarrel_focus_ar_coslo":"Marksman Foregrip",
 "t10_underbarrel_mixunder2_ar_coslo":"Ranger Foregrip",
 "t10_underbarrel_mixunder_ar_coslo":"Precision Foregrip",
 "t10_bar_mixbarrel_ar_coslo":"Reinforced Barrel",
 "t10_bar_velocity_ar_coslo":"Gain-Twist Barrel",
 "t10_stocks_mixstock2_ar_coslo":"Combat Stock",
 "t10_stocks_mixstock_ar_coslo":"Balanced Stock",
 "t10_mags_fastreload3_ar_coslo":"Fast Mag II",
 "t10_mags_fastreload_ar_coslo":"Fast Mag I",
 "t10_mags_extclip3_ar_coslo":"Extended Mag III",
 "t10_mags_extclip2_ar_coslo":"Extended Mag II",
 "t10_grips_mixgrip_ar_coslo":"Commando Grip",
 "jup_silencer_ar_06":"Sonic Suppressor",
 "t10_lasers_hipaccuracy_ar_coslo":"Steady Aim Laser",
 "t10_muzzles_mixmuzzle_ar_coslo":"Ported Compensator",
 "t10_muzzles_brake_ar_coslo":"Muzzle Brake",
 "t10_stocks_flinch_ar_coslo":"Heavy Stock",
 "t10_muzzles_suppressor_ar_coslo":"Suppressor",
 "t10_stocks_hipfiremove_ar_coslo":"Light Stock",
 "t10_stocks_adsmove_ar_coslo":"Infiltrator Stock",
 "t10_grips_sprintout_ar_coslo":"Assault Grip",
 "t10_grips_quickdraw_ar_coslo":"Quickdraw Grip",
 "t10_mags_extclip_ar_coslo":"Extended Mag I",
 "t10_muzzles_comp_ar_coslo":"Compensator",
 "jup_ammo_556n_rn":"5.56 NATO Round Nose",
 "jup_twofivex_golf36":"Houndeye Integrated Optic",
 "jup_jp01_ar_golf36_gunperks":"Ammo Category",
 "jup_jp01_ar_golf36_tuning":"Weapon Tuning",
 "jup_jp01_pgrip_tac":"NA",
 "jup_jp01_pgrip_ske":"NA",
 "jup_jp01_pgrip_snp":"NA",
 "jup_jp01_pgrip_aim":"NA",
 "jup_jp01_mag_40_556n":"NA",
 "jup_jp01_mag_20_556n":"NA",
 "jup_jp01_stockno":"NA",
 "jup_jp01_stock_assault":"NA",
 "jup_jp01_stock_skel":"NA",
 "jup_jp01_stock_heavy":"NA",
 "jup_jp01_stock_tacheavy":"NA",
 "jup_jp01_bar_short":"NA",
 "jup_jp01_bar_short_heavy":"NA",
 "jup_jp01_bar_fusion":"NA",
 "jup_jp01_bar_light":"NA",
 "jup_comp_ar_07":"T51R Billeted Brake",
 "jup_risr_twofivex01":"KR Marauder 9 Riser",
 "jup_jp01_ar_golf36_extras":"Laser Category",
 "jup_jp01_ar_golf36_reargrips":"Rear Grip Category",
 "jup_jp01_ar_golf36_muzzles":"Muzzle Category",
 "jup_jp01_ar_golf36_undermounts":"Underbarrel Category",
 "jup_jp01_ar_golf36_optics":"Optic Category",
 "jup_jp01_ar_golf36_magazines":"Magazine Category",
 "jup_jp01_ar_golf36_backpieces":"Stock Category",
 "jup_jp01_ar_golf36_frontpieces":"Barrel Category",
 "t10_bar_highcal_ar_coslo":"CHF Barrel",
 "t10_underbarrel_sway_ar_coslo":"Lightweight Foregrip",
 "t10_bar_range_ar_coslo":"Long Barrel",
 "t10_underbarrel_recoil_ar_coslo":"Vertical Foregrip",
 "grip_vert01":"Merc Foregrip",
 "ub_gl01":"SPW 40mm HE",
 "laserbox_ads02":"Schlager PEQ Box IV"
};